apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default
spec:
  controlNamespace: default
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: NodeAgent
metadata:
  name: fluentbit
spec:
  nodeAgentFluentbit: {}