kind: Logging
apiVersion: logging.banzaicloud.io/v1beta1
metadata:
  name: logging
spec:
  syslogNG:
    bufferVolumeMetrics:
      mount_name: buffers
      # prometheus chart or the operator should be installed for this to work
      serviceMonitor: true
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: syslog-ng
                volumeMounts:
                  - mountPath: /buffers
                    name: buffers
        volumeClaimTemplates:
          - metadata:
              name: buffers
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
