name: E2E tests

on:
  push:
    branches:
      - master
      - "release-[0-9]+.[0-9]+*"
  pull_request:

env:
  GO_VERSION: '1.20'
  KIND_VERSION: 'v0.19.0'
  KIND_NODE_VERSION: 'kindest/node:v1.23.17@sha256:f77f8cf0b30430ca4128cc7cfafece0c274a118cd0cdb251049664ace0dee4ff'
  KUBECTL_VERSION: 'v1.24.1'

jobs:
  build:
    name: Go end2end tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run e2e tests
        run: make test-e2e

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: go-e2e-test-cluster-logs
          path: build/_test
          retention-days: 5

  basic_flow:
    name: Shell script tests with chart install
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "${{ env.KIND_VERSION }}"
          image: "kindest/node:${{ env.KIND_NODE_VERSION }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stern
        run: make stern && test -x bin/stern

      - name: Build controller image
        run: make docker-build IMG='controller:local'

      - name: Create logging namespace
        run: kubectl create namespace logging

      - name: Start MinIO
        run: |
          kubectl create -f hack/minio.yaml
          kubectl wait --namespace logging --for=condition=available deployment/minio-deployment --timeout=120s
          minio="$(kubectl get pod --namespace logging -l app=minio -o 'jsonpath={.items[0].metadata.name}')"
          kubectl wait --namespace logging --for=condition=Ready pod "${minio}" --timeout=120s

      - name: Setup MinIO CLI
        run: |
          kubectl create -f hack/minio-mc.yaml
          kubectl wait --namespace logging --for=condition=available deployment/minio-mc-deployment --timeout=120s
          mc_pod="$(kubectl get pod --namespace logging -l app=minio-mc -o 'jsonpath={.items[0].metadata.name}')"
          kubectl wait --namespace logging --for=condition=Ready pod "${mc_pod}" --timeout=120s
          kubectl exec --namespace logging "${mc_pod}" -- \
            mc config host add minio \
            'http://minio-service.logging.svc.cluster.local:9000' \
            'minio_access_key' \
            'minio_secret_key'

      - name: Test
        run: hack/test.sh

      - name: Print last 10k kubernetes logs from default and logging namespaces
        if: always()
        run: |
          mkdir -p build/_test
          bin/stern -n default,logging ".*" --tail 100000 --no-follow > build/_test/cluster.logs

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: script-e2e-test-cluster-logs
          path: build/_test
          retention-days: 5
